services:
  - type: web
    name: passkey-todo-board
    runtime: ruby
    plan: starter
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server -p $PORT -e $RAILS_ENV
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: WEBAUTHN_ORIGIN
        sync: false
      - key: WEBAUTHN_RP_ID
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: passkey-todo-board-db
          property: connectionString
    disk:
      name: passkey-todo-board-disk
      mountPath: /opt/render/project/storage
      sizeGB: 1

databases:
  - name: passkey-todo-board-db
    databaseName: passkey_todo_board_production
    user: passkey_todo_board
    plan: starter

  - name: passkey-todo-board-redis
    plan: starter